### ISSUE TITLE
[Question] How to save/restore environment variables.

### ISSUE THREAD

**Issue by rvega** [tmux-plugins/tmux-resurrect#109]
I use a bunch of custom environment variables to set how my setup works, depending on which project I'm working on. If I do `export foo="Bar"` from a tmux pane, save the session, kill the tmux server, restart tmux and restore the session, the exported environment variables won't be there. Is there a way to do this? How?
Thanks for this great plugin! :)

**Comment by bruno-** [comment]
Hey,
glad you find this plugin useful :+1: . This feature is not supported.

My first thought related to this: setting up shell's environment is a job for the shell, not for `tmux` (or it's plugins). If I were trying to solve this, I'd probably script something in `.bashrc` or `zshrc` (whatever you're using).

Here's the idea how it might be solved (didn't test this though):

- make a file in the project directory (example name `.environment`) and put all env var statements in it `export foo="Bar"` etc
- when a shell is started in the project directory make it `source` the `.environment` file. Example code for `.bashrc`: `[ -f .environment ] && source .environment`

Please let us know if the above works or what approach you ended up with. It might help other users.

**Comment by bruno-** [comment]
Doing a little issues cleanup.
I think the previous comment answers the question so closing this issue. Feel free to reopen if you have any followups.

**Comment by cgr71ii** [comment]
> setting up shell's environment is a job for the shell, not for tmux (or it's plugins).

I don't totally agree with this assertion. It will be true for most of the plugins, of course, but I think it doesn't fit with this exact plugin. Since `tmux-resurrect`'s whole purpose is to be able to recover your **environment** in case you're going to restart the system or whatever other reason, doesn't make sense to try to have the closest version to our environment when we recover it using `tmux-resurrect`? Even this support has been extended to specific binaries like `man` or `htop`, but why can't be extended to environment variables? Only today, the day I've found this incredible plugin that fits exactly my needs (thank you for the plugin! :D), I've found >5 issues whose problems are actually related to environment variables, totally or partially.

@bruno- is this feature still, today, not being considered to be included? I know this is an old issue, but since I think it's not correct to comment at each issue with the related same problem (i.e. environment variables), I think this issue might be the beginning where I should ask.

**Comment by DavidEdell** [comment]
I also just discovered this useful plugin and had the same thoughts.  I agree this would be a useful feature (and I think within scope for this plugin), but I can see where it might also be problematic.


A simpler approach would be to add the ability to define a pane-specific script that should be sourced as part of the resurrection process.  A potential set of commands could be
- run-save $cmd.   # Prompt for a command.  Run it in the current pane AND save it somewhere so that it will be automatically re-executed if the pane is restored.  Optionally support this as a list of commands
- save $cmd.  # Same as above, but don't run it first.

Saving all the current env variables could take the form of a 'save-env' function (called automatically if enabled) that
- runs 'export' (or equivalent for current shell) to grab all env variables and save it to a file
- adds that file to this pane's resurrection command list if not already present.

Then again, I also spotted https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_bash_history.md - and I suspect a more reliable solution to that issue is a pre-requisite for this.

**Comment by devonjones** [comment]
My problem on this is that I use different env vars per window.  I basically have a window per aws account I work with and have to manually set the env vars per pane which is a pain (pun intended).

**Comment by MironVeryanskiy** [comment]
Likewise, I use environment variables in my tmux panes to define which target remote resources that pane will be operating against. I do not have associated directories for each tmux pane.

There exists precedent of tmux-resurrect supporting [restoration of applications](https://github.com/tmux-plugins/tmux-resurrect/blob/cff343cf9e81983d3da0c8562b01616f12e8d548/docs/restoring_programs.md#clarifications) and even a dedicated commitment to [restoring vim and neovim sessions](https://github.com/tmux-plugins/tmux-resurrect/blob/cff343cf9e81983d3da0c8562b01616f12e8d548/docs/restoring_vim_and_neovim_sessions.md). 

Although non-trivial in its scope due to needing to support various shell types and ephemeral environment variables, it would not be unreasonable to extend support for shell environment variables under the tmux-resurrect's stated goal to "Restore tmux environment after system restart."
