### ISSUE TITLE
How do you list all commands in a session? 

### ISSUE THREAD

**Issue by ceremcem** [tmux-plugins/tmux-resurrect#135]
Hello, 

I'm the author of [this](http://superuser.com/questions/1052271/how-to-list-last-commands-run-in-tmuxs-current-sessions-panes?noredirect=1#comment1475075_1052271) question on StackOverflow, where I try to find a way to list the last commands in current tmux session in order to generate a script that will resurrect that session. 

I need to generate a script, because I need to fire that tmux session in `/etc/rc.local` script, in boot time. 

I looked in `save.sh` but there is nothing I could find that you used to list current session's panes' last commands. 

Would you please lead me where you get these commands in a specific session?

**Comment by bruno-** [comment]
Hey,
I suggest first starting with `pane_current_command` built-in format. That's the way tmux enables you to get a command running in a given pane. Usage is described in `man tmux`.

Unfortunately, `pane_current_command ` is not perfect as it (for some reason) just doesn't detect all the commands running in panes. If you find it lacking you can check how it's done in this plugin. It's not perfect either and we've had some people complaining that they can't restore some commands (mostly from `node.js` world) but we didn't find a solution for this.

Anyway, you can start from [this line](https://github.com/tmux-plugins/tmux-resurrect/blob/370b4861cb73b9d78ff150472e248e48f104785f/scripts/save.sh#L209) in `save.sh`. By default it delegates to `save_command_strategies/ps.sh` script. This script uses the `ps` command and tmux pane pid (you get one with: `tmux display -F '#{pane_pid}'`) for better detection of processes running in tmux panes.

Since this issue is not really related to `tmux-resurrect` I'm going to close it. Hope the above explanation helps. Also, feel free to just copy any code you want from this project.
