### ISSUE TITLE
bash history restore

### ISSUE THREAD

**Issue by Goddard** [tmux-plugins/tmux-resurrect#137]
Following directions on this link https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_bash_history.md

For some reason it keeps outputting history -w into my terminal windows... Any help is appreciated.

ubuntu 14.04 using bash and I looked into my .bashrc and it has the recommended option enable ignoreboth.

**Comment by Goddard** [comment]
Testing in 16.04 in konsole and still same problem

**Comment by Zlopez** [comment]
I have the same issue on Fedora 24. It's writing "history -w in every tmux windows" every few minutes. This is really annoying.

**Comment by bruno-** [comment]
Guys, you probably have `tmux-continuum` installed and when it performs an automated save it runs this command (to save bash history) and that's the output you see.

This feature is clearly labeled experimental... it was left because some users were really persuasive. I personally don't like it. I recommend using it ONLY if you're ok with all the downsides (and yes, some users were ok with the symptoms you're getting).
