### ISSUE TITLE
tmux-strategy-vim 'session' does not work for me

### ISSUE THREAD

**Issue by yevhen-m** [tmux-plugins/tmux-resurrect#161]
`tmux-resurrect` does not restore my vim sessions.

```
tmux 2.2
nvim 0.1.6-dev
zsh 5.0.2
ubuntu 14.04
```

When I do `vim -S` (I have `nvim` aliased to `vim`) vim starts and loads my session as expected.

![image](https://cloud.githubusercontent.com/assets/10185058/19206757/dd707812-8cf3-11e6-8eea-56b83f33b758.png)

`.tmux.conf` part

```

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by Busimus** [comment]
Where is your `Session.vim` file?
Because tmux-resurrect will not run `vim` with ` -S` if it can't find that file in your home directory (at least that's how it works for me).
Vim usually puts `Session.vim` in your home directory, unless you have a line like `cd /home/username/somedir` in your .vimrc file. In that case it will be saved in that directory and the [script](https://github.com/tmux-plugins/tmux-resurrect/blob/b8cc90a7f4db209d6c25d4156f8f236eec3b1dca/strategies/vim_session.sh) won't be able to find it and it will run just `vim` instead.

**Comment by yevhen-m** [comment]
@Busimus why do you say that vim puts Session.vim files in home dirs?

If I start vim to work on my project say in `~/projects/foo/` then after `:mksession` vim will put Session.vim file in `~/projects/foo/`. And when I save my tmux session, this directory `~/projects/foo/` is saved for this terminal and after resurrect terminal is loaded in `~/projects/foo/`. Session.vim file is there, but vim is not started.

**Comment by Busimus** [comment]
@yevhen-m 
> why do you say that vim puts Session.vim files in home dirs?

I got it all confused because of vim-obsession. Forget all I wrote back there!

In any case, if the [script](https://github.com/tmux-plugins/tmux-resurrect/blob/b8cc90a7f4db209d6c25d4156f8f236eec3b1dca/strategies/vim_session.sh) can't find your Session.vim file in the directory it's running, then it will start Vim normally, which is what I assume is happening.
Try adding this line to the top of the main function in that script (`~/.tmux/plugins/tmux-resurrect/strategies/vim_session.sh`):
`echo "$DIRECTORY" > ~/out`
Then see what the `~/out` file contains.
