### ISSUE TITLE
Getting along with Solaris 11.x

### ISSUE THREAD

**Issue by wiscodisco** [tmux-plugins/tmux-resurrect#169]
I'm a tmux lover and Solaris 11.x user.  I needed to tweak tmux-resurrect in order to get it to save and am attaching the output of "git diff".

Please note, I didn't know the best way to abstract the "tr" command like the "ps" command has been abstracted in save_command_strategies/ps.sh.  So I simply changed the switch from -dC to -dc.  A cursory gla
[tmux-resurrect.diff.txt](https://github.com/tmux-plugins/tmux-resurrect/files/625358/tmux-resurrect.diff.txt)

nce at gnu tr seems the -C and -c are the same thing.

**Comment by wiscodisco** [comment]
Found an issue with restore.sh.   Many Solaris binaries are not GNU binaries (like FreeBSD and macOS).  In this case, awk (GNU) accepts the OFS command but plain awk (SunOS) doesn't.  I simply s/awk/gawk/ in scripts/restore.sh.   Many GNU binaries are available with a "pkg install text/*"

Again, there's probably a better way to abstract this.

**Comment by bruno-** [comment]
I'm all for increasing the compatibility especially as there's not a lot of changes.. but I'm a little discouraged because this issue has been open for half a year now and noone else joined the discussion or complained about Solaris support.. meaning there's not a lot of Solaris users that use tmux or tmux-plugins?

**Comment by wiscodisco** [comment]
It’s been 1900 days since I asked the question and it’s probably safe to close the issue.
