### ISSUE TITLE
@resurrect-processes does not work with `npm start`

### ISSUE THREAD

**Issue by bassamseif** [tmux-plugins/tmux-resurrect#201]
I have checked `~/.tmux/resurrect/last` apparently `npm start` is being saved as `:npm` rather than `:npm start` 
Added it manually and tried restoring it works, so the saving mechanism needs fixing

**Comment by bruno-** [comment]
There have been reports of wrongly saved process names for some javascript tools (grunt or gulp, don't remember now). Also, I just checked and I get the same for `npm run start` (the saved process name is just `npm`).

I think the issue here is the tool (`npm`) doesn't set the proper process name with all the arguments etc. And that's super easy to do, [check this](http://broken-by.me/node-js-change-visible-process-name/)!

Here's the fastest way to set a node process name:

```
$ node   # start node repl
> process.title = 'foo bar baz'
```

Now `ps -ef | grep foo` will show `foo bar baz` on a list of processes.

Anyway, I'd suggest contributing to `npm` as a proper solution for this one.

**Comment by unphased** [comment]
Thanks for the breadcrumbs @bruno- 

This seems still to be an issue as I see my npm processes saved as :npm in the file, so it's kind of a problem. 

I am thinking that if we inject the `process.title` setting from our application then it would be able to connect to a `->` process resurrection rule, right? e.g. we set `process.title` in our app to something really rather specific, and then the process resurrection rule can key off of that.

**Comment by unphased** [comment]
This doesn't work. See this process structure: 

```
├─ -zsh
│  ├─ -zsh
│  └─ npm
│     └─ sh -c PORT=3001 node scripts/start.js
│        └─ Custom process title
│           └─ /opt/nodejs/node-v12.18.3-linux-x64/bin/node --max-old-space-size=2048 /home/user/application/client/node_modules/react-dev-utils/node_modules/fork-ts-checker-webpack-plugin/lib/service.js
```

sucks :(

**Comment by bruno-** [comment]
Other people have solved this, check the docs https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md#nodejs

**Comment by unphased** [comment]
Yep I have looked at that section. I don't wanna come across the wrong way, but... yarn isn't npm. Some people may be able to switch to yarn, but it's sort of silly to assume everyone can. But I mostly understand the problem with npm at this point. It's with the code. I did make a PR there (you can see linked above). 

One thing I def wanted to swing back to mention is that a quick way to work around all of this silliness is to just make your own shell wrapper script to run. give it a useful name, and I'm thinking that resurrect should be able to save and restore the wrapper script! Easy.
