### ISSUE TITLE
Having issues recovering vim files opened in vim from same directory

### ISSUE THREAD

**Issue by sdondley** [tmux-plugins/tmux-resurrect#251]
I'm using `tmux-resurrect` and `tmux-contiuum` and the vim plugin, obsession.

The following works fine with two panes in tmux:

- `vim blah1.txt` in tmux pane 0
- **`cd some_dir` in tmux pane 1**
- `vim blah2.txt` in tmux pane 1
- I save tmux environment
- `tmux kill-server`
- `tmux start-server`
- `tmux attach -t 0`

Both vim files are restored in each tmux pane as expected.

The following does not work, however:

- `vim blah1.txt` in tmux pane 0
- `vim some_dir/blah2.txt` in tmux pane 1
- I save tmux environment
- `tmux kill-server`
- `tmux start-server`
- `tmux attach -t 0`

In the above scenario, when I don't first `cd` into the directory where blah2.txt is located, blah1.txt is shows in both panes.

**Comment by bruno-** [comment]
In the second scenario you're opening both vim instances from the same directory. vim will save session file `Session.vim` in the **same** dir. Depending on the order of session file creation, one will overwrite the other.

If you're using `set -g @resurrect-strategy-vim 'session'` in `~/.tmux.conf` maybe try removing that line. If vim `'session'` strategy is NOT used then resurrect will not try to restore vim from the session file. Instead, it will restore programs "literally". For example, in 2nd scenario, this plugin would run commands `vim blah1.txt` and `vim some_dir/blah2.txt` which should get you the desired results.

My suggestion is to just be careful how you save vim sessions, make sure you have 1 vim session file per directory and turn on `set -g @resurrect-strategy-vim 'session'` because it's overall much more useful.

**Comment by sdondley** [comment]
Thanks! Commenting out `set -g @resurrect-strategy-vim 'session'` did the trick. 

So what exactly am I losing by commenting that line out, though?

**Comment by bruno-** [comment]
That line improves vim integration by restoring whole vim sessions. Example:

- You use obsession.vim. Vim sessions are kept in `Session.vim` file in the directory where vim is started.
- When this plugin restores `vim` program, if it detects `Session.vim` file it will restore the whole vim session with `vim -S`.
- If line `set -g @resurrect-strategy-vim 'session'` is not present, this plugin will not make effort to check if `Session.vim` file exists and will not restore vim sessions.

If you're unsure what's even the deal with vim sessions: they remember the exact state of your running vim instance, down to the cursor position. So, if you start by `vim some_file.txt` but then open multiple other files in that process, vim session will remember all that.

**Comment by sdondley** [comment]
OK, thanks for the help. I think what I'll do is just use vim splits instead of tmux splits. But then I will lose the ability to easily jump to a numbered pane. Oh, well.

**Comment by vogler** [comment]
I ran into the same problem. My vim is setup to restore via mkview and loadview - I didn't use Session.vim before.
I often have several vim instances running in the same directory, so using a per-directory Session.vim is a no go.
I could continue not using sessions, but I like the idea of restoring window layouts and buffers opened from within vim.
Does someone have a better solution for this? Maybe store pid-identified sessions in a central place and make resurrect load those instead?
