### ISSUE TITLE
[Discussion/Thoughts] lazy load vim (or other processes) only when entering the session  after resurrecting

### ISSUE THREAD

**Issue by dylan-chong** [tmux-plugins/tmux-resurrect#255]
# Intro

So I have a really weird setup using tmux that probably not many other people use, so just a disclaimer --- maybe the issue I describe here isn't so important. I keep all of the windows, sessions, and [neo]vims open for all of the different projects are use --- including the ones that I haven't touched in six months, but plan on getting back to later. The setup is ready convenient because when I want to switch to the project, I don't have to worry about `cd`ing 

What this has ended up with is roughly 80 bash processes running, including 32 neovims (each of which has several tabs open). These all get started up when I restart my computer and then open tmux (I actually don't mind the wait time since I almost never reboot my computer). Now, the bash processes only use up roughly 2.8MB each, and the total 220MB isn't that much especially when it mostly can be written to swap. 

# Problem

Starting all the vim processes causes various other node and python processes to be started up. I have done my best to reduce this (by telling my linting plug-ins do not run when vim is started) but it seems these processes start even for syntax highlighting alone (so there's not much I can do about that). So this causes me to (apparently) to have roughly `123 python processes * 12MB + 37 node processes * 30MB = 1.5GB + 1.1GB = 2.6GB` of RAM used up by node and python processes. This sounds like a lot.

# Possible Solution

The most obvious solution would be to not keep all of my vims/sessions open all of the time. However, if I do this then I will lose the convenience of having the sessions there.

What I want to propose is the option to lazy load vims (or any other processes that the user could want automatically started only when opening the session for the first time). So specifically, when resurrecting the setup after a system restart, don't start a 'vim' process until the user navigates to the session that has vim in it. This would solve the RAM usage problem

---

Anyway, these are just some thoughts, hopefully ones that you found entertaining. This is not a critical problem as I guess most people don't do what I do, but would be interesting if it could be solved.

**Comment by bruno-** [comment]
Hi,

> I keep all of the windows, sessions, and [neo]vims open for all of the different projects are use --- including the ones that I haven't touched in six months, but plan on getting back to later. The setup is ready convenient because when I want to switch to the project, I don't have to worry about cding

This is the exact way I use this plugin. I have some projects I started years ago and they are still hanging around and restored each time.

> So this causes me to (apparently) to have roughly 123 python processes * 12MB + 37 node processes * 30MB = 1.5GB + 1.1GB = 2.6GB of RAM used up by node and python processes. This sounds like a lot.

Agreed, sounds like a problem.

> So specifically, when resurrecting the setup after a system restart, don't start a 'vim' process until the user navigates to the session that has vim in it. This would solve the RAM usage problem.

Why don't you try to hack a solution to this yourself? Here's how this could work:

- Do not restore vim/neovim process with this plugin. Remove it from the processes list.
- Create a tmux hook that would trigger on `client-session-changed` (If you keep projects organized via tmux sessions) and start a script.
- Script would:
  - Check if there is `Session.vim` file in the current working dir of the current session
  - If there is `Session.vim`, then send keys to the current tmux pane `vim -S` to restore vim session.

The above is just an idea. I actually haven't worked with tmux hooks yet.

<hr/>

>  However, if I do this then I will lose the convenience of having the sessions there.

I know automatic is best, but as another approach: you sure typing `vim -S` once per-project wouldn't work?

<hr/>

Another solution to this problem could be to re-evaluate your vim plugins/toolset. I hope you don't mind me saying, but this problem is clearly telling you have a bloated setup. If you keep your computer and tmux server started long enough to work briefly on all your projects, eventually you'll end up starting all those vim instances and related processes again.. Here's a couple hopefully constructive ideas:

- Can you replace python/node processes with something more light weight.. written in vim-script?
- Can you start python/node processes per project? Eg. run these subprocesses via projects' `.exrc` file?
- Can you just run these python/node processes manually from vim's command line, when needed?

**Comment by dylan-chong** [comment]
> Why don't you try to hack a solution to this yourself? Here's how this could work:
> 
> Do not restore vim/neovim process with this plugin. Remove it from the processes list.
> Create a tmux hook that would trigger on client-session-changed (If you keep projects organized via tmux sessions) and start a script.
> Script would:
> Check if there is Session.vim file in the current working dir of the current session
> If there is Session.vim, then send keys to the current tmux pane vim -S to restore vim session.

I have considered this, but this may be difficult because I have multiple windows in each session, only one of which runs neovim.

> I know automatic is best, but as another approach: you sure typing vim -S once per-project wouldn't work?

I already do this

> Another solution to this problem could be to re-evaluate your vim plugins/toolset. I hope you don't mind me saying, but this problem is clearly telling you have a bloated setup.

Aha! I had a look through the syntax highlighting code and I realised it wasn't the syntax highlighting that was creating all of these processes! I was able to figure out through `htop` that it is the plug-in `deoplete`and `vim-import-js` that is spawning most of the python and node processes. I'll have a look into these and see if I can get them to lazy load.

**Comment by dylan-chong** [comment]
I've managed to find a solution with `deoplete` too lazy load the python processes when entering insert mode, rather than when starting Vim; see here: https://github.com/Shougo/deoplete.nvim/issues/773 . Now 0 python processes start-up!

`vim-import-js` has just been updated to lazy load its node processes so a lot less node processes start up now https://github.com/Galooshi/vim-import-js/pull/42 

`ale`, a plug-in which is starting lots of `tsserver` node processes now has an open issue to lazy load tsserver 
https://github.com/w0rp/ale/issues/1619

**Comment by alchemmist** [comment]
@dylan-chong, right now I use a new tool, that completely solve this problem for me. This can save all sessions setup with running process and scrollback history and restore it lazy only when you first time go to some sessions. 

Maybe, it will be useful for you too:
https://lazy-tmux.xyz/
