### ISSUE TITLE
ipython3 not launching again while restoring

### ISSUE THREAD

**Issue by matheusfillipe** [tmux-plugins/tmux-resurrect#334]
tmux-ressurrect works with all the commands that i had on my session and wanted to reload except by ipython... idk what is so specific about it or if that is really a bug. Here is my config:

```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-processes 'ssh psql mysql sqlite3 python python3 R sudo htop ssh nethogs su python3 ipython3 ipython R cling nctelegram dmesg ipython3 proxy shairport-sync watch journalctl zsh'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
set -g mouse on
#mne_in_modeouse_any_flag

```

Im on tmux 3.0a arch linux.

**Comment by jiaming10** [comment]
I came across this documentation just now, maybe it can help?
https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md#clarifications-

**Comment by matheusfillipe** [comment]
> I came across this documentation just now, maybe it can help?
> https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md#clarifications-

Thanks! I might have been too lazy on this one, my fault. For anyone who maybe stumble upon here with this same problem what i did was adding "~ipython3" to my ressurrect-processes list: like this

```
set -g @resurrect-processes 'ssh psql mysql sqlite3 sudo htop ssh nethogs su R cling nctelegram dmesg "~ipython3" proxy shairport-sync watch journalctl zsh nvtop bashtop'
```

**Comment by jiaming10** [comment]
Don't blame yourself, because I just found out this documentation after more than a year using tmux-resurrect. Mainly I because I never tried to restore my running programs. =p

In fact, I should be thanking you because this is the second issue that I read wanting to restore programs (the "first" being https://github.com/tmux-plugins/tmux-resurrect/issues/337). That makes me thought "oh people actually want to restore their programs?", and there I went and stumbled upon the docs.

So yeah, I'm glad that we helped each other. =D
