### ISSUE TITLE
Doesn't play cool with byobu

### ISSUE THREAD

**Issue by shivams** [tmux-plugins/tmux-resurrect#61]
I installed this plugin and saved my session. 

After rebooting, I opened byobu, which uses tmux as the backend. Inside byobu, I was unable to restore my session. 

I then tried a different approach. I open tmux first. Restored my session. Then detached from tmux. Then, I opened byobu. Now, byobu was not opening in its original form. It was behaving exactly the same as tmux. Its custom keybindings and other custom features were not working. 

Kindly look into it. This issue makes byobu totally unusable with tmux.

**Comment by bruno-** [comment]
Hi,
doing a little issues cleanup. It's been almost a year since the discussion here took place so closing this one. Feel free to reopen if there are any followups to this.

**Comment by learningjs** [comment]
Hi,

first of all congratulations for the great plugins!

I am experiencing the same issue. I am quite new to tmux, byobu, tmux-resurrect and tmux-continuum (directly using the last one).

Basically everything was working as I'd expect: I was able to detach from byobu and reconnect opening the saved session right in byobu. 

But after rebooting, I encounter now this issue: when I launch byobu, there is not session available (ok, I guess this is natural, not having tmux starting on boot). If I launch tmux I am able to restore the saved session, but then byobu behaves just like tmux (looks like I am directly in tmux, not in byobu). 

Sorry, I do not know what else I can report about it, may be with some hint I can further explore the issue and give more details about it.

**Comment by chuim** [comment]
I would also be very happy to see tmux-ressurrect working properly with byobu.

**Comment by falzard** [comment]
does it work with byobu? is there a solution???

**Comment by cgr71ii** [comment]
@falzard I've tested Byobu and it seems to work as expected. Can anyone else confirm this? It's the first time I'm using `tmux-resurrect` and I might have missed something.

**Comment by ip413** [comment]
"Nothing" works as expected. The list of issues is so long that there is no point in writing it down.
I have tmux / byobu configured on another system and there it works fine, but as I remember it took hours or even days to configure it correctly. Right now, on new system I'm not able to make both working even with configs from the old system.
I have a feeling like many bugs were related to some kind of race condition, because how it works - I can't predict what will happen when I start it next time. It's strange. It's very difficult to understand what is going on - at least for me.

**Comment by cgr71ii** [comment]
Well, today I installed a new environment with Byobu and this plugin and, again, works. In case that someone wants to give it a try, this is what I usually do:

```bash
sudo apt install byobu
byodu
byobu-enable
nano ~/.byobu/.tmux.conf # no ~/.tmux.conf as indicated in the installation
```
Content I use in `~/.byobu/.tmux.conf` (in a clean installation I see the file empty):
```
# List of plugins
set -g @tpm_plugins '      	\
  tmux-plugins/tpm         	\
  tmux-plugins/tmux-sensible   \
  tmux-plugins/tmux-resurrect  \
  tmux-plugins/tmux-continuum  \
'

# Plugins conf
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-save-interval '60'
set -g history-limit 100000

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

Then I just close all my byobu panels in order to initiate a new bash process and it works (see the attached image).

If someone could confirm, it'd be nice.

![Captura de pantalla de 2024-03-24 11-30-38](https://github.com/tmux-plugins/tmux-resurrect/assets/16403611/46d02383-5cbd-4e31-95e0-24d5e57a6897)

EDIT:

I forgot to mention that I first installed https://github.com/tmux-plugins/tpm following the instructions:

```bash
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
```

Then update `~/.tmux.conf`:

```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

Then close and open a new byobu environment, follow the steps I said in the original comment, press `prefix`+`I` to install the plugins, and I can use `prefix`+`ctrl+s` and `prefix`+`ctrl+r`.

**Comment by fredericgermain** [comment]
I'm not sure why, I'm on Ubuntu 22.04, and the loaded byobu config is in `.config/byobu/`, so the file to edit is `.config/byobu/tmux.conf`.

Hope it helps

**Comment by ip413** [comment]
This is insane. I had to reinstall my system, so I'm trying on a new install, this time: Fedora 40. It doesn't work. In short. I wasn't even able to restore manually saved session. Plugins seems to be installed correctly. But, there is a mess. I don't want to dive in it.

I don't want to spend hours in debugging what is going on. Description "how to" is not useful it paths are different, and if instructions' order is reversed.

Sorry and thank you.

(probably something related to proper paths, which could be ~ or ~/.config for .tmux.conf or / and byobu and tmux dirs - too many options, I wasn't able to find proper one, I'm not going to waste a minute more) 

----- EDIT
Ok, I decided to spend some time to set it up and I did it.
In short:

Remove all dirs and configs you could have, which are ~/.byobu ~/.config/byobu ~/.tmux.conf ~/.tmux ~/.config/tmux
There is several steps:
1. install byobu (it is installed with tmux as dependency)
2. create dirs for tmux
3. clone tpm into tmux dir
4. edit tmux config file
5. install tmux plugins
6. check if continuum works
7. check if resurrect works

After every step with cloning, installing, saving, it's good to check if specific files are created, downloaded.

```bash

sudo dnf install byobu


# check if works

byobu

# kill tmux-server

tmux kill-server


# move .tmux.conf to ~/.config/byobu/.tmux.conf or edit it and run byobu
# you should get errors '~/.tmux/plugins/tpm/tpm' returned 127

# create ~/.tmux/ directory

mkdir -p ~/.tmux/plugins ~/.tmux/resurrect

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

tmux kill-server


# syntax from .tmux.conf
# #set -g @plugin 'tmux-plugins/tmux-yank'
# doesn't work for some reason!!!
# use 
# set -g @tpm_plugins ' \
#     tmux-plugins/tpm \
#     tmux-plugins/tmux-yank \
#     tmux-plugins/tmux-sensible \
#     tmux-plugins/tmux-resurrect \
#     tmux-plugins/tmux-continuum \
#     '

# run byobu
byobu

# install plugins (ctrl+b or ctrl+a, depending on your config)
ctrl+b      Shift+i


# you should see something like:
#
# Already installed "tpm"                   [0/0]
# Installing "tmux-yank"                         
#   "tmux-yank" download success                 
# Installing "tmux-sensible"                     
#   "tmux-sensible" download success             
# Installing "tmux-resurrect"                    
#   "tmux-resurrect" download success            
# Installing "tmux-continuum"                    
#   "tmux-continuum" download success            
# 
# TMUX environment reloaded.                     
# 
# Done, press ENTER to continue.

# never enough
tmux kill-server

byobu

# Now you should see in bottom right "Tmux resurrect file not found" which is pretty good!

# To save session manually
CTRL + b       CTRL + s

# You should see "Tmux environment saved!"


# Saved sessions should be placed in /home/___USER___/.tmux/resurrect

```

My .tmux.conf (there is a mess because I was trying to moving, deleting, adding different things; ):
```
set -g status-justify right
set -g default-terminal "screen-256color"
set -g history-limit 500000

unbind -n MouseDown3Pane

unbind C-a
set-option -g prefix C-b
bind-key C-b send prefix
set-window-option -g xterm-keys on

bind -T copy-mode-vi y send -X copy-pipe "xclip -selection c"

set -g base-index 1

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins/"
set -g @tpm_plugins ' \
   tmux-plugins/tpm \
   tmux-plugins/tmux-yank \
   tmux-plugins/tmux-sensible \
   tmux-plugins/tmux-resurrect \
   tmux-plugins/tmux-continuum \
   '

set -g @continuum-save-interval '1'
set -g @continuum-restore 'on'
set -g mouse on
set -g @continuum-boot 'on'
bind e setw synchronize-panes on
bind E setw synchronize-panes off
set -g status on

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins/"
set -g @resurrect-dir '/home/as/.tmux/resurrect'

run -b '~/.tmux/plugins/tpm/tpm'
```
