### ISSUE TITLE
Multiple linked tmux sessions, once saved, become restored as separated sessions

### ISSUE THREAD

**Issue by unphased** [tmux-plugins/tmux-resurrect#71]
A common workflow of mine is I set up a tmux session on my Macbook, and then in order to leverage tmux for extra screen space, SSH from another machine and connect using `tmux new-session -t <name>`. This **shares** the session with the existing one, while allowing filling the screen (if i view two different windows). I.e. they are different sessions but they share the running processes!

Now once I have this whole thing set up if I use resurrect to save and then subsequently restore it after my machine reboots for example, what happens is two **separate** sessions of similar initial configuration are created!

So this obviously leads to spawning twice as many instances of shells and other restored apps. And it's a mess that I have to clean up.

Maybe what i need is a way to configure the bind such that when i save a session, it will only save the current session instead of all sessions. More properly, it should only take the set of separate sessions and not save any of the "linked" sessions.

**Comment by bruno-** [comment]
Hi,
thank you for reporting this. This seems like an example of somewhat advanced workflow.

> This shares the session with the existing one, while allowing filling the screen (if i view two different windows).

I just played a little bit with `tmux new-session -t <name>`. What is the advantage or use case of using that command over `tmux attach -t <name>`? It seems as if the first command just creates `new-session` and other things are similar or the same?

While we're at it, I \*think* this "window sharing" can be manually accomplished with commands like `move-window` or `link-window`. So you'd get the same window being present in 2 sessions. `tmux-resurrect` would double those windows too.
That said, I've never found a use case for this feature.

**Comment by unphased** [comment]
Well, the advantage is nil if you have a single monitor. But once you want to connect to one machine with multiple monitors (whether from the same machine or multiple, it works equally well) the advantage is clear... 

Say youve got a session with two windows. If your second session is just regularly attached (`attach -t <name>`) instead of "attached" with `new-session -t <name>`, you end up with mirrored tmux. Switch window on one of your terminal emulators, and the other follows. 

But if you use `new-session -t <name>` you also land on the same window initially (such that they are mirrored) but the non-attachment allows you to switch to the OTHER tmux window, and at this point you can simultaneously independently interact with both tmux windows (as you have two terminals viewing them). Tmux treats this very elegantly by freeing the terminal size constraint in this case also. When mirroring, Tmux limits the window size to that of the smallest attached terminal window.

Hope this is starting to make some sense...

**Comment by bruno-** [comment]
Hey - yes this does make sense. Thank you for the thorough explanation. I don't have the multi-monitor setup but the scenario you describe can still easily be reproduced with 2 terminal windows.

So do you have any idea how this should be handled?
How about saving and restoring \*only the original session*. The session additionally created with `new-session -t <name>` would be ignored (not saved or restored), since it can easily be created again with the same command if needed.
How does that sound?

**Comment by unphased** [comment]
Yes! That's how i would approach it, because trying to figure out which sessions are "shadow sessions" sounds like a dicey proposition (unless there already exists an easy way to fetch them).

**Comment by bruno-** [comment]
Hey,
I pushed what seems to be working code for this in "grouped_sessions" branch (tmux manpage calls this "grouped sessions"). If you want you can try it and let me know how it works.
I'll test the code myself tomorrow.

I changed the implementation from what we were talking above (for the better I think). So, the job of this plugin is to restore tmux state \*exactly as it was*. Instead of not restoring "shadow sessions", `tmux-resurrect` should now properly restore them in their "shadow" state - so no duplicate panes and windows.

**Comment by unphased** [comment]
That's awesome, I'll test it and let you know.

**Comment by bruno-** [comment]
Hi @unphased,
we're now saving "current" and "alternate" windows for grouped sessions. All the work is pushed to `grouped_sessions` branch.

I did some testing and all was working fine. If you can confirm all looks good on your end, that would be great.
Either way, I'll merge this to master tomorrow.
Thanks

**Comment by unphased** [comment]
Great, I just tested and it did the right thing!

**Comment by bruno-** [comment]
Great, thank you. This code is now pushed to master.
