### ISSUE TITLE
MacVim's vim won't resurrect 

### ISSUE THREAD

**Issue by phorust** [tmux-plugins/tmux-resurrect#75]
Hey all,

I have the problem in #72 as well, but the fixes discussed above didn't help. Vim simply won't run on resurrecting a session. I'm running the vim binary from the MacVim distribution (for YouCompleteMe support), not sure if that has anything to do with it. I'm also using tmux 1.9a and vim 7.4 inside iTerm, with `tmux attach -t base || tmux new -s base` as my "Send text at start" option.

The fix
```
set-option -g default-command "reattach-to-user-namespace -l $SHELL"
```
doesn't work for me

My `.tmux.conf` file is here: [test](https://github.com/phorust/dotfiles/blob/master/tmux.conf)

Here are the contents of my ~/.tmux/resurrect/last file:

```
pane	base	0	:reattach-to-user-namespace	1	:*	0	:/Volumes/MacintoshHD/Users/phorust	0	zsh	:
pane	base	0	:reattach-to-user-namespace	1	:*	1	:/Volumes/MacintoshHD/Users/phorust/git/dotfiles	1	Vim	:/Applications/MacVim.app/Contents/MacOS/Vim makeMyselfAtHome.sh
pane	base	1	:.	0	:-	0	:/Volumes/MacintoshHD/Users/phorust	1	htop	:htop
window	base	0	1	:*	e4da,181x55,0,0{90x55,0,0,1,90x55,91,0,2}
window	base	1	0	:-	c300,181x55,0,0,3
state	base	base
```

**Comment by phorust** [comment]
Just checked with OS X's default vim (I saved the binary as vim_default) and it also won't resurrect. `vim_default -S` and `vim -S` both work and reopen my Obession session from the Session.vim file.

```
pane	base	0	:.	1	:*	0	:/Volumes/MacintoshHD/Users/phorust/git/dotfiles	1	vim_default	:vim_default -S
window	base	0	1	:*	c300,181x55,0,0,3
state	base	base
```

**Comment by bruno-** [comment]
Hey, thanks for taking the time to report this.

From what I can see from `~/.tmux/resurrect/last` file, `mvim` process is saved as this command: `/Applications/MacVim.app/Contents/MacOS/Vim makeMyselfAtHome.sh` (that's second row, last field value after colon).

I'm guessing that `mvim` script is just a wrapper and is delegating "real" macvim opening to that command (wild guess, could be wrong).
Anyway, since this long command `/Applications/MacVim.app...` is not on the list of commands to be restored, well - it's not restored.

Here's a couple solutions we can try to make it work:
- first, can you verify executing this commands from the shell opens macvim properly: `$ /Applications/MacVim.app/Contents/MacOS/Vim makeMyselfAtHome.sh`. If yes, then we want that command to be restored. Please extend your `resurrect-processes` tmux option so it looks like this:

        set -g @resurrect-processes 'vim mvim "git log" "~MacVim.app"'

  Note the tilde before the MacVim.app. That means that any process that matches that string will be restored.

- if manually executing that long command from the shell fails, maybe we can try this approach:

        set -g @resurrect-processes 'vim mvim "git log" "~MacVim.app->mvim"'

  This should invoke `mvim` command whenever `MacVim.app` string is matched with the saved command. Hopefully that makes sense.

**Comment by bruno-** [comment]
About the second attempt to restore vim saved as `vim_default` binary. I think this is a similar as the first issue. `vim_default` is not on the `@resurrect-processes` list and is therefore not restored.
Can you try adding it to that list and see if it works?

Also, please note that strategy for restoring `vim's` sessions works best if `vim` executable is used. I'm not sure it will work with `vim_default`.

**Comment by phorust** [comment]
Awesome, setting
```
set -g @resurrect-processes 'vim mvim "git log" "~MacVim.app"'
```
did restore my vim processes (after I saved, ran `tmux kill-server`, `tmux new -s base`, and restored).

As a side note, running `$ /Applications/MacVim.app/Contents/MacOS/Vim makeMyselfAtHome.sh` did indeed work for me. Thanks for the quick help!

**Comment by neo1691** [comment]
@bruno-  I had the exact same problem and this solution solved it for me. However I am getting a bad rendering after tmux-resurrect is restoring the vim session. There are lot of unwanted spaces. I think the redrawing after the restoring of vim sessions is not working properly. It may be caused due to some bad configuration. 

This is the screenshot: 

![screenshot 2017-08-16 12 49 20](https://user-images.githubusercontent.com/1628340/29355724-bb74c460-828f-11e7-8070-6ec5254cdedc.png)


Here is my [.tmux.conf](https://gist.github.com/neo1691/99dc13e8b90b8ef9fcdff1509d4e709f) and here is my .[vimrc](https://gist.github.com/neo1691/bfffd2fa65168157a94c1a8cf26a1597)

Any help or suggestions are greatly appreciated. 

Thanks

**Comment by bruno-** [comment]
@neo1691 your `tmux.conf` looks ok. I checked your `.vimrc` and it looked ok, but I'm less confident with it because of all the plugins I'm not familiar with.

I'm not using macvim but here's what I would try if I had to debug this:

- Empty out your `.vimrc` and leave everything else the same. Then try restore. If the result is not good, then the error (or improvement to be made) is likely somewhere in your `.vimrc`
- What is the command used to restore that window from the screenshot? My guess is it's something like `mvim -S` (the `-S` flag to restore vim session)? What happens when you quit that window and restore it by manually typing that command?

**Comment by neo1691** [comment]
@bruno- 

Here are the contents of `last`

```
pane	dev	1	:Vim	0	:-	1	:/Users/neo1691	1	Vim	:/usr/local/Cellar/macvim/8.0-136/MacVim.app/Contents/bin/../MacOS/Vim -g -v .vimrc
pane	dev	2	:top	1	:*	1	:	1	top	:top
pane	dev	2	:top	1	:*	2	:/Users/neo1691	0	bash	:
window	dev	1	0	:-	b3bd,158x41,0,0,0
window	dev	2	1	:*	5d2b,158x41,0,0{79x41,0,0,1,78x41,80,0,2}
state	dev	
```

I ran the following command `/usr/local/Cellar/macvim/8.0136/MacVim.app/Contents/bin/../MacOS/Vim -g -v .vimrc`  both outside and inside a tmux session and vim operated correctly. 

I also tried to open vim with a blank `vimrc` and it still didn't solve my problem. 

I think it has to do with something else. Let me know if you need to run any more tests on this.

**Comment by bruno-** [comment]
Honestly I don't know what could be wrong here. Everything in your `last` file looks ok.

The only unusual thing is you're running MacVim instead of the "regular", raw terminal vim. I didn't even know you can run MacVim in terminal. I have it installed but it always opens in a GUI.

After you have macvim opened with those blank spaces how do you get it back to normal rendering? You just start moving the cursor a little bit until it's good?

**Comment by neo1691** [comment]
No when I start moving the cursor, the blanks still stay there. I have to quit and restart vim. 

Indeed this is a problem with MacVim. In my older MBP I am using `neovim` and `tmux-ressurect` works just fine.
