### ISSUE TITLE
tmux resurrect not resurrecting latest; seems to be resurrecting *current* session

### ISSUE THREAD

**Issue by jzacsh** [tmux-plugins/tmux-resurrect#91]
`C-r` (resurrect) gives me "tmux-restore" message as usual, but when it completes, it doesn't seem to have done anything. That is: I can open any configuration of windows with random names like "foo" "bar" and "baz" and `C-r` completes with a success message, but everything is intact.

### debug info
see my `~/.tmux.conf` and `~/.tmux/resurrect/last` -> `tmux_resurrect_2015-07-17T19:57:39.txt` contents here: https://gist.github.com/jzacsh/45c83999e984cfa64694

tried to gather as much detail as I thought would be helpful [here at aciinema.org: ![asciinema termal recording thumbnail](https://asciinema.org/a/6cpcra8926dhuyrsyflp00k2r.png)](https://asciinema.org/a/6cpcra8926dhuyrsyflp00k2r)
_(note: `tmux` without the `-L main` option doesn't resolve my issue)_

### what I tried
I followed some debugging from issue #29, but didn't see anything that helped me fix this issue

Anyway, any thoughts on what I might try to debug this? I poked around the `restore.sh` logic, and some simple things look correct _(ie: I manually ran a handful of restore-related calls to [`tmux show-option -gvq`](https://github.com/tmux-plugins/tmux-resurrect/blob/e81f8e5f37a7f20afde9e5edcdc2c43249967a01/scripts/helpers.sh#L9) calls, but output looks normal to me)_

**Comment by bruno-** [comment]
Hey,
thanks for the detailed data (file contents and an ascii vid in the report)!

I think [initialization from the tmux.conf](https://gist.github.com/jzacsh/45c83999e984cfa64694#file-tmux-conf-L26-L29) might be clashing with tmux-resurrect. Here's what I \*think* is happening:

1. when tmux is started, a couple windows are created from `tmux.conf` (lines linked above)
2. a second or so after tmux is started, `tmux-continuum` auto-restore kicks in and starts restoring
3. resurrect is idempotent [link to readme section](https://github.com/tmux-plugins/tmux-resurrect#about) meaning it won't try restoring or manipulating windows / panes that already exist. Since a couple windows were created in step 1. those windows won't be overridden in any way.

Could it be the above is the reason for this issue?
For the sake of debugging I recommend commenting out these [lines from tmux.conf](https://gist.github.com/jzacsh/45c83999e984cfa64694#file-tmux-conf-L26-L29) and try doing a restore and see what happens.

**Comment by bruno-** [comment]
Also, looking at your `last` file, you have a few non-standard processes that won't be restored by default. More info about which processes are restored by default and other config can be found [here](https://github.com/tmux-plugins/tmux-resurrect#configuration).

Basically you can:

- put this line in tmux.conf to restore \*all* programs that are running inside tmux:

        set -g @resurrect-processes ':all:'

- OR explicitly enable each process that should be restored (recommended). Looking at your `tmux.conf` that would look something like this:

        set -g @resurrect-processes 'ncmpcpp "~ grc tail" ~java'

**Comment by jzacsh** [comment]
Yes, now that I've re-read your explanations (and readme's) I see I had just brushed over some important points previously - this is totally my fault/misunderstanding. Thank you for clarifying.

Everything is working **perfectly** now! _(and my `tmux.conf` is a tiny bit healthier for it :P )_

Thanks again for the quick response, bruno, much appreciated!
