### ISSUE TITLE
Make it work with Tmuxinator

### ISSUE THREAD

**Issue by blacksky86** [tmux-plugins/tmux-resurrect#96]
I am not sure if I'm mistaking this, but is there a way to make it work with tmuxinator configs? I have a few different sessions and every time I save it and try to restore it, it just goes back to the original one. Meaning it will only save one session details. If i'm on another session, it will just detach me and get me into the saved one. It there support for it or maybe plans for future implementation?

**Comment by bruno-** [comment]
Hey,
I'm not sure if we have a real problem here or this is just a misunderstanding how things work.

- `tmux-resurrect` should always save **all** the sessions
- when saving, active session, window and pane are remembered (active means what the user is looking at in the terminal where the save happens)
- active session, window and pane will be restored in the terminal window where the restore was triggered from (I think this might explain why you get attached to the "saved session" after restore)

After you perform the restore try using `prefix - s` (it's tmux's built-in binding) to switch to some other session and verify if everything is there.

Please report if something looks off and I'll try to help.

**Comment by blacksky86** [comment]
hmm, probably there is some confusion on my part. Let me try to elaborate, not sure if you use tmuxinator.

Say I create a new session "mux new foo" and then it has it's own little setup. I am happy with it and save it "Ctrl+s" . But then I create another project and create a new session "mux new bar", this time when I'm inside of "bar", if I hit "Ctrl+r" it restores the "foo" setup and it is only able to remember the last active setup. 

So where I'm getting at is if there is a way to save different setups for project "foo", "bar", "baz"... And when we use tmuxinator to get into "baz" for example, we hit the "Ctrl-r" and only restore the last saved setup of "baz" not of the others. 

Sorry if I'm misunderstanding, I'm not a tmux pro :/ . And thank you for the answer and time :) .

**Comment by bruno-** [comment]
Ah, ok... I can confirm saving/restoring individual tmux sessions ("projects" in tmuxinator vocabulary) is not supported.
Implementing this would certainly add complexity and I'm not clear on the benefits.

Why not just keep all the sessions (projects) running all the time and save/restore all of them? This is cheap in terms of resources..

**Comment by blacksky86** [comment]
Ah okay, I think I will try it the other way around and just eliminate tmuxinator. Seems what you suggested is best in the end anyways. Thanks!

**Comment by ramiroaraujo** [comment]
@bruno- @blacksky86 jumping in! in my opinion, the benefits would be to be able to have multiple tmux setups ready to jump back to business. I also though it would be great to have some kind of integration with tmuxinator, but then though it would be better to manage this internally. Both approaches are different:
tmuxinator approach: would mean some way to serialize the tmux-resurrect info in a tmuxinator file, probably easy to do with the windows and panes setup, but probably not possible with initialization scripts.
internal approach: basically a CRUD for saving the sessions with a name. 

Not sure about the complexity of the second approach, I started playing with it a few weeks ago but didn't find time to keep going. 
The first approach might make sense as a shortcut for creating tmuxinator configs.

**Comment by bruno-** [comment]
> the benefits would be to be able to have multiple tmux setups ready to jump back to business

"tmux setups" is a little vague, do you mean tmux sessions? I still fail to see what's the problem here: tmux-resurrect enables you to save all open tmux sessions. After restore, all sessions will be restored so you can jump to any one of the "businesses" you were working on previously.

To take a step back, I don't see why would you want to use both `tmuxinator` and `tmux-resurrect` at the same time. Essentially, they both do the same thing: automate tmux so you get desired layouts fast. Pick one tool you like and that's it. No need to fiddle with both.

Maybe I should write a guide for users migrating for tmuxinator...

**Comment by bruno-** [comment]
Hey guys,
I made a guide for migrating from [tmuxinator to tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/migrating_from_tmuxinator.md).

Feedback is welcome!

**Comment by ramiroaraujo** [comment]
@bruno- I see your point! I though tmux-resurrect would save only ONE tmux session, the current one I was working on.

Although I *love* the resurrect plugin, I think I would find more useful to save each individual session, and then be able to load each one as needed. Of course that would also need listing and a way to delete them. Would you consider a PR for that approach?

**Comment by blacksky86** [comment]
Yeah, that post helped me out, thanks @bruno- . I removed tmuxinator and see the light :smile:  . Will keep an eye out for what @ramiroaraujo comes out with it thought. Thanks!

**Comment by bruno-** [comment]
@blacksky86, glad it helped.

@ramiroaraujo, I know you won't like this, but I wouldn't be too enthusiastic to accept the PR at this point. Not only it would add new features, but it would be hard to keep the existing "interface" relatively simple (having just 2 straightforward key bindings).

If you guys really want this, do you think there are enough ppl out there that would upvote this? Also please comment on the benefits of having this feature (not just for the sake of having the same workflow as `tmuxinator`).

Lastly, if you really want this, why not fork this plugin and make a new one that is focused on saving/restoring sessions? Feel free to rename the plugin so the difference is emphasized. If it works nicely and proves to be useful, I'd be glad to link to it from the readme or something.

**Comment by ramiroaraujo** [comment]
@bruno- :) Currently with tmuxinator I'm able to have several setup for ongoing projects, many with some heavy duty processes going on. I don't like the idea of having all those sessions kicked-off when I would only need one. I'll fork and work on this variant and then we'll see ;), I can always rename it later into a new plugin.

**Comment by bruno-** [comment]
Sounds good.
It seems we're ok to close this issue.
